### ISSUE TITLE
Add python 3.7

### ISSUE THREAD

**Issue by damianavila** [conda-forge/rise-feedstock#14]
Ref: https://github.com/damianavila/RISE/issues/406

**Comment by damianavila** [comment]
@ocepaf, I opened https://github.com/conda-forge/rise-feedstock/pull/17 expecting to have python 3.7 packages, but I think I missing something, any ideas?

**Comment by ocefpaf** [comment]
We are doing the automatic migration to 3.7 together with the new compilers, so it may take a while. I can "hack" conda-smithy and send a point 3.7 update here later. Hold on...
